# Julia Basics

## Quantecon Workshop at Chilean Central Bank - 2022


### What is Julia

- developped at MIT on top of opensource technologies
    - linux / git / llvm
- syntax inspired by Matlab but:
    - more consistent
    - lots of features from high level languages
- everything is JIT-compiled
    - interpreted vs compiled treadeoff
    - -> very fast
    - most of the base library is written in Julia
- opensource/free + vibrant community


Some useful links from QuantEcon:

* [Julia cheatsheet](https://cheatsheets.quantecon.org/julia-cheatsheet.html)
* [Julia-Matlab comparison](https://cheatsheets.quantecon.org/index.html)
* [Julia essentials](https://lectures.quantecon.org/jl/julia_essentials.html)
* [Vectors, arrays and matrices](https://lectures.quantecon.org/jl/julia_arrays.html)

Excellent resources at: [julialang](https://julialang.org/learning/)
- checkout JuliaAcademy, it's free
- ongoing [MOOC](https://computationalthinking.mit.edu/Spring21/) at MIT

### an example of what you shouldn't do in Matlab

How I learnt: interpreted code is slow, so vectorize your code.

In [3]:
function stupid_loop(I,J,K)
    t = 0.0
    for i=1:I
        for j=1:J
            for k = 1:K
                t += 1.0
            end        
        end
    end
    return t
end


stupid_loop (generic function with 1 method)

In [4]:
@time [ stupid_loop(1000,1000,i) for i =1:10]

  0.161749 seconds (59.85 k allocations: 3.129 MiB, 56.31% compilation time)


10-element Vector{Float64}:
 1.0e6
 2.0e6
 3.0e6
 4.0e6
 5.0e6
 6.0e6
 7.0e6
 8.0e6
 9.0e6
 1.0e7

In [5]:
@time [ stupid_loop(1000,1000,i) for i =1:10]

  0.091901 seconds (41.99 k allocations: 2.170 MiB, 29.45% compilation time)


10-element Vector{Float64}:
 1.0e6
 2.0e6
 3.0e6
 4.0e6
 5.0e6
 6.0e6
 7.0e6
 8.0e6
 9.0e6
 1.0e7

Code is translated to LLVM code then to instructions for the processor. Note that processor instructions are shorter than LLVM code.

In [6]:
@code_llvm stupid_loop(10,10000000000,100000000000000)

;  @ /home/pablo/Econforge/NoLib/notebooks/Julia_Basics.ipynb:1 within `stupid_loop`
define double @julia_stupid_loop_1339(i64 signext %0, i64 signext %1, i64 signext %2) #0 {
top:
;  @ /home/pablo/Econforge/NoLib/notebooks/Julia_Basics.ipynb:3 within `stupid_loop`
; ┌ @ range.jl:5 within `Colon`
; │┌ @ range.jl:393 within `UnitRange`
; ││┌ @ range.jl:400 within `unitrange_last`
     %.inv = icmp sgt i64 %0, 0
     %. = select i1 %.inv, i64 %0, i64 0
; └└└
  br i1 %.inv, label %L17.preheader, label %L94

L17.preheader:                                    ; preds = %top
  %.inv26 = icmp sgt i64 %1, 0
  %.24 = select i1 %.inv26, i64 %1, i64 0
  %.inv27 = icmp sgt i64 %2, 0
  %.25 = select i1 %.inv27, i64 %2, i64 0
;  @ /home/pablo/Econforge/NoLib/notebooks/Julia_Basics.ipynb:4 within `stupid_loop`
  %3 = select i1 %.inv26, i1 %.inv27, i1 false
  br i1 %3, label %L35.preheader.split.us.us.us, label %L94

L81.us.us:                                        ; preds = %L68.us.us.us
;  @ /home/p

In [8]:
@code_native stupid_loop(10,10,10)

	.text
	.file	"stupid_loop"
	.section	.rodata.cst8,"aM",@progbits,8
	.p2align	3                               # -- Begin function julia_stupid_loop_1741
.LCPI0_0:
	.quad	0x3ff0000000000000              # double 1
	.text
	.globl	julia_stupid_loop_1741
	.p2align	4, 0x90
	.type	julia_stupid_loop_1741,@function
julia_stupid_loop_1741:                 # @julia_stupid_loop_1741
; ┌ @ /home/pablo/Econforge/NoLib/notebooks/Julia_Basics.ipynb:1 within `stupid_loop`
	.cfi_startproc
# %bb.0:                                # %top
	vxorpd	%xmm0, %xmm0, %xmm0
; │ @ /home/pablo/Econforge/NoLib/notebooks/Julia_Basics.ipynb:3 within `stupid_loop`
; │┌ @ range.jl:5 within `Colon`
; ││┌ @ range.jl:393 within `UnitRange`
; │││┌ @ range.jl:400 within `unitrange_last`
	testq	%rdi, %rdi
; │└└└
	jle	.LBB0_9
# %bb.1:                                # %L17.preheader
	testq	%rsi, %rsi
; │ @ /home/pablo/Econforge/NoLib/notebooks/Julia_Basics.ipynb:4 within `stupid_loop`
	jle	.LBB0_9
# %bb.2:                       

### Syntax Review

#### Variable assignment

Assignement operator is = (equality is ==, identity is ===)

In [ ]:
# Assign the value 10 to the variable x
x = 10

In [ ]:
2 == 3

In [9]:
# Variable names can have Unicode characters
# To get ϵ in the REPL, type \epsilon<TAB>
ϵ = 1e-4

4

Default semantic is pass-by-reference:

In [14]:
a = [1,2,3,4]
b = a
a[1] = 10
b

4-element Vector{Int64}:
 10
  2
  3
  4

To work on a copy: `copy` or `deepcopy`

In [17]:
a = [1,2,3,4]
b = copy(a)
a[1]=10
b

4-element Vector{Int64}:
 1
 2
 3
 4

In [18]:
a .== b

4-element BitVector:
 0
 1
 1
 1

In [ ]:
a === b

#### Basic types

In [20]:
# for any object `typeof` returns the type
?typeof

ErrorException: syntax: invalid identifier name "?"

In [19]:
typeof(a)

Vector{Int64} (alias for Array{Int64, 1})

#### Numbers

In [21]:
y = 2 + 2

4

In [23]:
a_i = 1000
a_f = 1000.0

1000.0

In [ ]:
-y

In [ ]:
0.34*23

In [22]:
3/4

0.75

In [ ]:
# Scalar multiplication doesn't require *
3(4 - 2)

In [ ]:
x = 4
2x

In [ ]:
typeof(x)

In [ ]:
sizeof(a)

#### Booleans

In [29]:
false

false

Equality

In [30]:
0 == 1

false

In [ ]:
2 != 3

In [ ]:
3 <= 4

Identity

In [ ]:
a = [34, 35]
b = [34, 35]
c = a

In [ ]:
c === a

In [ ]:
b === a

Boolean operator

In [ ]:
true && false

In [ ]:
true || false

In [ ]:
!true

#### Strings

In [31]:
# Strings are written using double quotes
str = "This is a string 🦈"

"This is a string 🦈"

In [ ]:
ch = 'k' # this is a character

In [ ]:
# Strings can also contain Unicode characters
fancy_str = "α is a string"

In [32]:
# String interpolation using $
# The expression in parentheses is evaluated and the result is 
# inserted into the string
a = 2+2
"2 + 2 = $(a)"

"2 + 2 = 4"

In [ ]:
println("It took me $(a) iterations")

In [ ]:
# String concatenation using *
"hello" * "world"

In [ ]:
println("hello ", "world")

#### Arrays

Julia has one-dimensional homogenous arrays. They are also called Vector.

In [ ]:
A = [1, 4]

2-element Vector{Float64}:
 1.0
 4.0

All elements have the same type (and are coerced is needed):

In [10]:
A = [1, 1.4]

2-element Vector{Float64}:
 1.0
 1.4

In [38]:
eltype(A)

Float64

In [39]:
typeof(A) 

Vector{Float64} (alias for Array{Float64, 1})

In [41]:
A''

2-element Vector{Float64}:
 1.0
 4.0

To get the size of an array:

In [42]:
size(A)

(2,)

Arrays are *mutable*

In [43]:
A[1] = 10

10

In [21]:
A

2-element Array{Float64,1}:
 10.0
  1.4

Julia has one-based indexing: you refer to the first element as 1 ($\neq$ zero-based indexing in C or Python)

In [22]:
A[2]

1.4

Arrays are mutable and their size can be changed too:

In [44]:
push!(A, 29)

3-element Vector{Float64}:
 10.0
  4.0
 29.0

In [27]:
A

3-element Array{Float64,1}:
 10.0
  1.4
 29.0

Two comments:
- the `push!` operation is *fast*
- `!` is a julia convention to express the fact that `push!` mutates its first argument

#### tuples

In [32]:
size(A)  # is a tupled

(3,)

In [47]:
# you can create tuples with (,,,)
t = (1,2,3,4)


(1, 2, 3, 4)

tuples differ from arrays in two ways:
- they are immutable
- they can contain non-homogenous objects

In [48]:
t[1]

1

In [49]:
t[1] = 2

MethodError: MethodError: no method matching setindex!(::NTuple{4, Int64}, ::Int64, ::Int64)

In [51]:
tt = (1, "1", [1])

(1, "1", [1])

In [52]:
typeof(tt)

Tuple{Int64, String, Vector{Int64}}

#### Named tuples

Named tuples are tuple with field names. Note that the semi-colon separates positional arguments from keyword arguments.

In [ ]:
t = (;a=0.2, b=0.1)

0×0×0×0×0×0 Array{Float64, 6}

In [ ]:
t

#### Array operations

##### Other ways to construct arrays:

In [73]:
# zero array
t = zeros(2,3)
t[1,2] = 23.2
t

2×3 Matrix{Float64}:
 0.0  23.2  0.0
 0.0   0.0  0.0

In [75]:
# random array (uniform distribution)
t= rand(3,3)
t

3×3 Matrix{Float64}:
 0.570885  0.8465    0.752361
 0.770423  0.882113  0.0953965
 0.228185  0.95713   0.133111

In [14]:
# random array (normal distribution)
t= randn(3,3)
t

3×3 Matrix{Float64}:
 -0.377592  -1.1838    -3.03421
  0.222662   0.67289   -0.951637
  1.71749   -0.474052   1.13057

Vectorized operations take a ., even comparisons (pointwise operations)

In [78]:
B = [1 2 ; 3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

In [79]:
B .* B

2×2 Matrix{Int64}:
 1   4
 9  16

In [ ]:
Remark: the convention that `.` denotes vectorized operations extends to all functions.

In [80]:
f(x) = x^2+1

f (generic function with 1 method)

In [82]:
f(43.0)

1850.0

In [83]:
f.(B)

2×2 Matrix{Int64}:
  2   5
 10  17

Elements are always accessed with square brackets:

In [85]:
B = [1 2 3; 4 5 6]

2×3 Matrix{Int64}:
 1  2  3
 4  5  6

In [ ]:
You get element $B_{ij}$ with `B[i,j]`

In [86]:
B[2,3]

5

Linear indexing is also allowed

In [ ]:
B[4]

You select a whole row/column with `:`

In [87]:
B

2×3 Matrix{Int64}:
 1  2  3
 4  5  6

In [88]:
B[:,1]

2-element Vector{Int64}:
 1
 4

In [89]:
B[1,:]

3-element Vector{Int64}:
 1
 2
 3

In [90]:
B[:,1:2]

2×2 Matrix{Int64}:
 1  2
 4  5

In [91]:
B[:,1:end-1]

2×2 Matrix{Int64}:
 1  2
 4  5

#### Control flow

Conditions

In [66]:
x = 0
if x<0
    # block
    println("x is negative")
elseif (x > 0) # optional and unlimited
    println("x is positive")
else         # optional
    println("x is zero")
end

x is zero


While

In [67]:
i = 3
while i > 0
    println(i)
    i -= 1 # decrement
end

3
2
1


For loops: one can iterate over any iterable object:
- range   `i1:i2`, `range(0,1; length=100)`
- vector
- tuple
- iterator ...

In [92]:
# Iterate through ranges of numbers
for i ∈ (1:3)
    println(i)
end

1
2
3


In [93]:
# Iterate through arrays
cities = ["Boston", "New York", "Philadelphia"]
for city in cities
    println(city)
end

Boston
New York
Philadelphia


In [74]:
cities

3-element Array{String,1}:
 "Boston"
 "New York"
 "Philadelphia"

In [95]:
states = ["Massachussets", "New York", "Pennsylvania"]

3-element Vector{String}:
 "Massachussets"
 "New York"
 "Pennsylvania"

In [96]:
two_by_two_iterable = zip(cities, states)

zip(["Boston", "New York", "Philadelphia"], ["Massachussets", "New York", "Pennsylvania"])

In [97]:
collect(two_by_two_iterable)

3-element Vector{Tuple{String, String}}:
 ("Boston", "Massachussets")
 ("New York", "New York")
 ("Philadelphia", "Pennsylvania")

In [98]:
# Iterate through arrays of tuples using zip
for kw in zip(cities, states)
    println(kw)
end

("Boston", "Massachussets")
("New York", "New York")
("Philadelphia", "Pennsylvania")


In [79]:
# Iterate through arrays of tuples using zip
for (city, state) in zip(cities, states)
    println("$city, $state")
end

Boston, Massachussets
New York, New York
Philadelphia, Pennsylvania


In [81]:
# Iterate through arrays and their indices using enumerate
for (i, city) in enumerate(cities)
    println("City $i is $city")
end

City 1 is Boston
City 2 is New York
City 3 is Philadelphia


#### Array comprehensions

The list comprehension syntax creates arrays (with homogenous types).

In [ ]:
[i^2 for i  ∈ 1:10] # collect with comprehension syntax

10-element Vector{Int64}:
   1
   4
   9
  16
  25
  36
  49
  64
  81
 100

In [101]:
[1:10 ...]  # unpack operator

10-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [85]:
[i^2 for i=1:10 if mod(i,2)==0]

5-element Array{Int64,1}:
   4
  16
  36
  64
 100

In [ ]:
Logic extends to several dimensions to create vectors.

In [ ]:
[i+j for i=1:10, j=1:10]

#### Iterators

Like in python, an "iterator" can be created with round brackets and can be composed with other iterators.

In [ ]:
iterator = ( i^2 for i=1:10 if mod(i,2)==0 )

Base.Generator{Base.Iterators.Filter{var"#20#22", UnitRange{Int64}}, var"#19#21"}(var"#19#21"(), Base.Iterators.Filter{var"#20#22", UnitRange{Int64}}(var"#20#22"(), 1:10))

Generators are not supported (yet). Or are they?

### Data Types and multiple dispatch

#### Composite types

A **composite type** is a collection of named fields that can be treated as a single value. They bear a passing resemblance to MATLAB structs.

All fields must be declared ahead of time. The double colon, `::`, constrains a field to contain values of a certain type. This is optional for any field.

In [103]:
# Type definition with 4 fields
struct ParameterFree
    value  
    transformation  
    tex_label
    description 
end

In [104]:
pf = ParameterFree("1", x->x^2, "\\sqrt{1+x^2}", ("a",1))

ParameterFree("1", var"#23#24"(), "\\sqrt{1+x^2}", ("a", 1))

In [106]:
pf.value

"1"

Two reasons to create structures:
- syntactic shortcut (you access the fields with .)
- specify the types of the fields

In [115]:
# Type definition
struct Parameter
    value ::Float64
    transformation ::Function # Function is a type!
    tex_label::String
    description::String
    stddev:: Float64
end

ErrorException: invalid redefinition of constant Parameter

In [111]:
p = Parameter("1", x->x^2, "\\sqrt{1+x^2}", "Crucial Parameter")

MethodError: MethodError: Cannot `convert` an object of type String to an object of type Float64
Closest candidates are:
  convert(::Type{T}, !Matched::T) where T<:Number at number.jl:6
  convert(::Type{T}, !Matched::Number) where T<:Number at number.jl:7
  convert(::Type{T}, !Matched::Base.TwicePrecision) where T<:Number at twiceprecision.jl:273
  ...

In [112]:
p = Parameter(0.43, x->x^2, "\\sqrt{1+x^2}", "This is a description")

Parameter(0.43, var"#31#32"(), "\\sqrt{1+x^2}", "This is a description")

In [113]:
p.value

0.43

When a type with $n$ fields is defined, a constructor (function that creates an instance of that type) that takes $n$ ordered arguments is automatically created. Additional constructors can be defined for convenience.

In [104]:
# Creating an instance of the Parameter type using the default
# constructor
β = Parameter(0.9, identity, "\\beta", "Discount rate")

Parameter(0.9, identity, "\\beta", "Discount rate")

In [125]:
function Parameter(value)
    return Parameter(value, x->x, "x", "Anonymous")
end

Parameter

In [126]:
Parameter(0.4)

Parameter(0.4, var"#33#34"(), "x", "Anonymous")

In [127]:
Parameter(value, transformation, tex) = Parameter(value, transformation, tex, "no description")

Parameter

In [128]:
methods( Parameter )

# 4 methods for type constructor:
[1] Parameter(value::Float64, transformation::Function, tex_label::String, description::String) in Main at /home/pablo/Econforge/NoLib/notebooks/Julia_Basics.ipynb:3
[2] Parameter(value) in Main at /home/pablo/Econforge/NoLib/notebooks/Julia_Basics.ipynb:1
[3] Parameter(value, transformation, tex) in Main at /home/pablo/Econforge/NoLib/notebooks/Julia_Basics.ipynb:1
[4] Parameter(value, transformation, tex_label, description) in Main at /home/pablo/Econforge/NoLib/notebooks/Julia_Basics.ipynb:3

In [110]:
# Alternative constructors end with an appeal to the default
# constructor
function Parameter(value::Float64, tex_label::String)
    transformation = identity
    description = "No description available"
    return Parameter(value, transformation, tex_label, description)
end

α = Parameter(0.5, "\alpha")

Parameter(0.5, identity, "\alpha", "No description available")

Now the function `Parameter` has two different `methods` with different signatures:

In [9]:
methods(Parameter)

# 4 methods for type constructor:
[1] Parameter(value::Float64, transformation::Function, tex_label::String, description::String) in Main at In[1]:3
[2] Parameter(value::Float64, tex_label::String) in Main at In[8]:4
[3] Parameter(value, transformation, tex) in Main at In[5]:1
[4] Parameter(value, transformation, tex_label, description) in Main at In[1]:3

We have seen that a function can have several implementations, called methods, for different number of arguments, 
or for different types of arguments.

In [129]:
fun(x::Int64, y::Int64) = x^3 + y

fun (generic function with 1 method)

In [132]:
fun(x::Float64, y::Int64) = x/2 + y

fun (generic function with 2 methods)

In [130]:
fun(2, 2)

10

In [117]:
fun(2.0, 2)

3.0

In [ ]:
α.tex_label

In [118]:
# Access a particular field using .
α.value

0.5

In [ ]:
# Fields are modifiable and can be assigned to, like 
# ordinary variables
α.value = 0.75

### Mutable vs non mutable types


by default structures in Julia are non-mutable

In [123]:
p.value = 3.0

LoadError: setfield! immutable struct of type Parameter cannot be changed

In [124]:
mutable struct Params
    x:: Float64
    y:: Float64
end

In [125]:
pos = Params(0.4, 0.2)

Params(0.4, 0.2)

In [126]:
pos.x = 0.5

0.5

### Parameterized Types

**Parameterized types** are data types that are defined to handle values identically regardless of the type of those values.

Arrays are a familiar example. An `Array{T,1}` is a one-dimensional array filled with objects of any type `T` (e.g. `Float64`, `String`).

In [133]:
[45,76]

2-element Vector{Int64}:
 45
 76

In [134]:
[45,76.0]

2-element Vector{Float64}:
 45.0
 76.0

In [135]:
# Defining a parametric point
struct Duple{T} # T is a parameter to the type Duple
    x::T
    y::T
end

In [136]:
Duple(3, 3)

Duple{Int64}(3, 3)

In [137]:
Duple(3.0, -1.0)

Duple{Float64}(3.0, -1.0)

In [138]:
Duple(3.0, -1)

MethodError: MethodError: no method matching Duple(::Float64, ::Int64)
Closest candidates are:
  Duple(::T, !Matched::T) where T at ~/Econforge/NoLib/notebooks/Julia_Basics.ipynb:3

In [29]:
struct Truple{T}
    x::Duple{T}
    z::T
end

This single declaration defines an unlimited number of new types: `Duple{String}`, `Duple{Float64}`, etc. are all immediately usable.

In [30]:
sizeof(3.0)

8

In [31]:
sizeof( Duple(3.0, -15.0) )

16

In [ ]:
# What happens here?
Duple(1.5, 3)

In [35]:
struct Truple3{T,S}
    x::Tuple{T,S}
    z::S
end

We can also restrict the type parameter `T`:

In [37]:
typeof("S") <: Number

false

In [38]:
typeof(4) <: Number

true

In [40]:
# T can be any subtype of Number, but nothing else
struct PlanarCoordinate{T<:Number}
    x::T
    y::T
end

In [41]:
PlanarCoordinate("4th Ave", "14th St")

MethodError: MethodError: no method matching PlanarCoordinate(::String, ::String)

In [42]:
PlanarCoordinate(2//3, 8//9)

PlanarCoordinate{Rational{Int64}}(2//3, 8//9)

Arrays are an exemple of mutable, parameterized types

### Why Use Types?

You can write all your code without thinking about types at all. If you do this, however, you’ll be missing out on some of the biggest benefits of using Julia.

If you understand types, you can:

- Write faster code
- Write expressive, clear, and well-structured programs (keep this in mind when we talk about functions)
- Reason more clearly about how your code works

Even if you only use built-in functions and types, your code still takes advantage of Julia’s type system. That’s why it’s important to understand what types are and how to use them.

In [139]:
# Example: writing type-stable functions
function sumofsins_unstable(n::Integer)  
    sum = 0:: Integer
    for i in 1:n  
        sum += sin(3.4)  
    end  
    return sum 
end  

function sumofsins_stable(n::Integer)  
    sum = 0.0 :: Float64
    for i in 1:n  
        sum += sin(3.4)  
    end  
    return sum 
end

# Compile and run
sumofsins_unstable(Int(1e5))
sumofsins_stable(Int(1e5))

-25554.110202663698

In [140]:
@time sumofsins_unstable(Int(1e5))

  0.000239 seconds


-25554.110202663698

In [141]:
@time sumofsins_stable(Int(1e5))

  0.000147 seconds


-25554.110202663698

In `sumofsins_stable`, the compiler is guaranteed that `sum` is of type `Float64` throughout; therefore, it saves time and memory. On the other hand, in `sumofsins_unstable`, the compiler must check the type of `sum` at each iteration of the loop. Let's look at the LLVM [intermediate representation](http://www.johnmyleswhite.com/notebook/2013/12/06/writing-type-stable-code-in-julia/).

In [143]:
@code_warntype sumofsins_stable(Int(1e5))

MethodInstance for sumofsins_stable(::Int64)
  from sumofsins_stable(n::Integer) in Main at /home/pablo/Econforge/NoLib/notebooks/Julia_Basics.ipynb:10
Arguments
  #self#::Core.Const(sumofsins_stable)
  n::Int64
Locals
  @_3::Union{Nothing, Tuple{Int64, Int64}}
  sum::Float64
  i::Int64
Body::Float64
1 ─       (sum = Core.typeassert(0.0, Main.Float64))
│   %2  = (1:n)::Core.PartialStruct(UnitRange{Int64}, Any[Core.Const(1), Int64])
│         (@_3 = Base.iterate(%2))
│   %4  = (@_3 === nothing)::Bool
│   %5  = Base.not_int(%4)::Bool
└──       goto #4 if not %5
2 ┄ %7  = @_3::Tuple{Int64, Int64}
│         (i = Core.getfield(%7, 1))
│   %9  = Core.getfield(%7, 2)::Int64
│   %10 = sum::Float64
│   %11 = Main.sin(3.4)::Core.Const(-0.2555411020268312)
│         (sum = %10 + %11)
│         (@_3 = Base.iterate(%2, %9))
│   %14 = (@_3 === nothing)::Bool
│   %15 = Base.not_int(%14)::Bool
└──       goto #4 if not %15
3 ─       goto #2
4 ┄       return sum



### Multiple Dispatch

So far we have defined functions over argument lists of any type. Methods allow us to define functions “piecewise”. For any set of input arguments, we can define a **method**, a definition of one possible behavior for a function.

In [51]:
# Define one method of the function print_type
function print_type(x::Number)
    println("$x is a number")
end

print_type (generic function with 1 method)

In [53]:
# Define another method
function print_type(x::String)
    println("$x is a string")
end

print_type (generic function with 2 methods)

In [54]:
# Define yet another method
function print_type(x::Number, y::Number)
    println("$x and $y are both numbers")
end

print_type (generic function with 3 methods)

In [55]:
# See all methods for a given function
methods(print_type)

# 3 methods for generic function "print_type":
[1] print_type(x::String) in Main at In[53]:3
[2] print_type(x::Number) in Main at In[51]:3
[3] print_type(x::Number, y::Number) in Main at In[54]:3

Julia uses **multiple dispatch** to decide which **method** of a **function** to execute when a function is applied. In particular, Julia compares the types of _all_ arguments to the signatures of the function’s methods in order to choose the applicable one, not just the first (hence "multiple").

In [56]:
print_type(5)

5 is a number


In [57]:
print_type("foo")

foo is a string


In [58]:
print_type([1, 2, 3])

MethodError: MethodError: no method matching print_type(::Array{Int64,1})
Closest candidates are:
  print_type(!Matched::String) at In[53]:3
  print_type(!Matched::Number) at In[51]:3
  print_type(!Matched::Number, !Matched::Number) at In[54]:3

#### Other types of functions

Julia supports a short function definition for one-liners

In [153]:
f(x) = x^3

f (generic function with 3 methods)

In [154]:
f(3.0)

9.0

In [146]:
f(x::Float64) = x^2.0
f(x::Int64) = x^3

f (generic function with 3 methods)

In [155]:
methods(f)

# 3 methods for generic function "f":
[1] f(x::Float64) in Main at /home/pablo/Econforge/NoLib/notebooks/Julia_Basics.ipynb:1
[2] f(x::Int64) in Main at /home/pablo/Econforge/NoLib/notebooks/Julia_Basics.ipynb:2
[3] f(x) in Main at /home/pablo/Econforge/NoLib/notebooks/Julia_Basics.ipynb:1

As well as a special syntax for anonymous functions

In [156]:
u -> u^2

#35 (generic function with 1 method)

In [159]:
((u,v) -> (u+v)^2)( 4.4, 4)

70.56

In [160]:
map(u->u^2, [1,2,3,4])

4-element Vector{Int64}:
  1
  4
  9
 16

In [ ]:
Note that anonymous functions have very small overhead if any.

In [ ]:
A = range(-10, 10; length=100000)
maximum(u->u-(u-0.4)^2, A) 
# better than maximum(A.-(A.-0.4).^2) 


### Keyword arguments and optional arguments

In [4]:
g(a,b,c=true; algo="newton") = c ? a + b : a-b

g (generic function with 2 methods)

In [8]:
g(2,3)

5

In [10]:
g(2,3, true; algo = :JI)

5

### Packing/unpacking


In [60]:
t = (1,2,4)

(1, 2, 4)

In [61]:
a,b,c = t

(1, 2, 4)

In [65]:
[(1:10)...]

10-element Array{Int64,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [66]:
cat([4,3], [0,1]; dims=1)

4-element Array{Int64,1}:
 4
 3
 0
 1

In [67]:
l = [[4,3], [0,1], [0, 0], [1, 1]]
# how do I concatenate it ?

cat(l...; dims=1) ### see python's f(*s)

8-element Array{Int64,1}:
 4
 3
 0
 1
 0
 0
 1
 1

Since 1.8, there is a special syntax to create named tuple, and unpack objects.

In [27]:
a = 1
b = 2
c = 3
t = (;a, b, c) # equivalent to (;a=1,b=2,c=3)

(a = 1, b = 2, c = 3)

In [28]:
a = b = c = 0

0

In [31]:
(;a, b, c) = t 
# equivalent to
# a = t.a
# b = t.b
# c = t.c
@show (a,b,c)

(a, b, c) = (1, 2, 3)


(1, 2, 3)

### Writing Julian Code

As we've seen, you can use Julia just like you use MATLAB and get faster code. However, to write faster and _better_ code, attempt to write in a “Julian” manner:

- Define composite types as logically needed
- Write type-stable functions for best performance
- Take advantage of multiple dispatch to write code that looks like math
- Add methods to existing functions

### Just-in-Time Compilation

How is Julia so fast? Julia is just-in-time (JIT) compiled, which  means (according to [this StackExchange answer](http://stackoverflow.com/questions/95635/what-does-a-just-in-time-jit-compiler-do)):

> A JIT compiler runs after the program has started and compiles the code (usually bytecode or some kind of VM instructions) on the fly (or just-in-time, as it's called) into a form that's usually faster, typically the host CPU's native instruction set. _A JIT has access to dynamic runtime information whereas a standard compiler doesn't and can make better optimizations like inlining functions that are used frequently._

> This is in contrast to a traditional compiler that compiles all the code to machine language before the program is first run.

In particular, Julia uses type information at runtime to optimize how your code is compiled. This is why writing type-stable code makes such a difference in speed!

## Exercise:

Define 3x3 matrix `M` with biggest eigenvalue smaller than 1. 
Consider Ar1 process $X_t = M X_{t-1} + E_t$ where E_t follows a standard normal distribution.
Simulate for T=1000 periods starting with $X_0=[0,0,0]$. Compute 1000 draws to approximate the standard deviation of the ergodic distribution.

Compare the performance of different programming styles using BenchmarkTools:
- matlab-like
- in-place
- using local variables
- using static arrays
